## These two functions together create an object that stores a matrix and the
## inverse of that matrix, and provides an easy method for retrieving both.

## makeCacheMatrix takes as argument a single matrix and returns a list
## of four items. The first, set, is a function for setting the value of the matrix
## after the object is created, and removes any stored value of the inverse
## whenever the matrix is changed. The second, get, is a function that returns
## the stored matrix. The third, setsolve, is a function used separately store
## the inverse of the stored matrix, but does not calculate it. The fourth,
## getsolve, is a function that returns the stored value of the inverse.
## The <<- operator is used to pass variables defined within these functions
## to the environment of makeCacheMatrix, clearing any stored value of the
## inverse whenever set() is called and setting the argument of set() as the
## stored matrix in the list that makeCacheMatrix returns.

makeCacheMatrix <- function(x = matrix()) {
        inverse <- NULL
        set <- function(var) {
                x <<- var
                invert <<- NULL
        }
        get <- function() x
        setsolve <- function(solve) inverse <<- solve
        getsolve <- function() inverse
        list(set = set, get = get, setsolve = setsolve,
        getsolve = getsolve)
}


## cacheSolve takes as argument a list generated by makeCacheMatrix and returns
## the inverse of the matrix stored therein. It checks whether the inverse
## has already been calculated for the stored matrix. If this has been done,
## it returns the stored matrix from memory. Otherwise, it calculates the
## inverse of the stored matrix and returns it to the getsolve position in the
## list it took as argument.

cacheSolve <- function(x, ...) {
        inverse <- x$getsolve()
        if(!is.null(inverse)) {
                message("getting cached data")
                return(inverse)
        }
        data <- x$get()
        inverse <- solve(data, ...)
        x$setsolve(inverse)
        inverse
}
